name: Python Execution Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 5'

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Clone london-cycles-db repository
      run: |
        git clone https://github.com/fferegrino/london-cycles-db.git --depth 1 --branch main
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install polars==1.15.0
    
    - name: Run Python script
      run: |
        python rollup.py

    - name: Commit changes
      run: |
        msg="Updated: `date +'%Y-%m-%d %H:%M'`"
        git config --global user.email "antonio.feregrino+datasets@gmail.com"
        git config --global user.name "Antonio Feregrino"
        git add data/
        git diff --quiet && git diff --staged --quiet || git commit -m "$msg"
        git push
